# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 14:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import record.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('type_video', '\u89c6\u9891'), ('type_phtoto', '\u6444\u5f71'), ('type_travel', '\u6e38\u8bb0'), ('type_program', '\u7f16\u7a0b')], max_length=20, verbose_name='\u7c7b\u578b')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=record.models.pic_upload_path, verbose_name='\u5c01\u9762')),
                ('article_description', models.TextField(blank=True, null=True, verbose_name='\u6982\u89c8')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u6b63\u6587')),
                ('video', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u89c6\u9891\u94fe\u63a5')),
                ('date', models.DateField(verbose_name='\u53d1\u5e03\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u8bb0\u5f55',
                'verbose_name_plural': '\u6211\u7684\u6d41\u6c34\u8d26',
            },
        ),
    ]
