# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-19 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import record.models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_img', models.ImageField(blank=True, null=True, upload_to=record.models.pic_upload_path, verbose_name='\u6444\u5f71\u56fe\u7247')),
                ('remarks', models.CharField(max_length=20)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Record')),
            ],
        ),
    ]
