# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 13:52
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': '\u8bb0\u5f55', 'verbose_name_plural': '\u6211\u7684\u6d41\u6c34\u8d26'},
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 15, 13, 52, 19, 156121, tzinfo=utc), verbose_name='\u53d1\u5e03\u65e5\u671f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='main_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2016, 9, 15, 13, 52, 32, 808070, tzinfo=utc), verbose_name='\u6b63\u6587'),
            preserve_default=False,
        ),
    ]
