# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-19 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_recordimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordimg',
            name='remarks',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
