# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_record_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='main_body',
        ),
        migrations.AlterField(
            model_name='record',
            name='article_description',
            field=models.TextField(blank=True, verbose_name='\u5168\u6587\u6982\u89c8'),
        ),
        migrations.AlterField(
            model_name='record',
            name='video',
            field=models.CharField(max_length=200, verbose_name='\u89c6\u9891\u94fe\u63a5'),
        ),
    ]
