# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 14:33
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20160915_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(verbose_name='\u53d1\u5e03\u65e5\u671f'),
        ),
    ]
