# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20160915_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10, verbose_name='\u7c7b\u578b\u540d\u79f0')),
                ('type_key', models.CharField(max_length=10, verbose_name='\u7c7b\u578b\u5173\u952e\u5b57')),
            ],
            options={
                'verbose_name': '\u8bb0\u5f55\u7c7b\u578b',
            },
        ),
    ]
