# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_recordtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordtype',
            name='type_key',
            field=models.CharField(max_length=15, verbose_name='\u7c7b\u578b\u5173\u952e\u5b57'),
        ),
    ]
