# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-02 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_auto_20161102_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='\u59d3\u540d'),
            preserve_default=False,
        ),
    ]
