# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_auto_20160918_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_type',
        ),
    ]
