# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_record_record_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordtype',
            options={'verbose_name': '\u8bb0\u5f55\u7c7b\u578b', 'verbose_name_plural': '\u8bb0\u5f55\u7c7b\u578b'},
        ),
    ]
