# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0017_auto_20160918_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(blank=True, choices=[('type_video', '\u89c6\u9891'), ('type_phtoto', '\u6444\u5f71'), ('type_travel', '\u6e38\u8bb0'), ('type_program', '\u7f16\u7a0b')], default='', max_length=1, verbose_name='\u8bb0\u5f55\u7c7b\u578b'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecordType',
        ),
    ]
