# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import record.models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0022_auto_20160918_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='article_description',
            field=models.TextField(blank=True, null=True, verbose_name='\u6982\u89c8'),
        ),
        migrations.AlterField(
            model_name='record',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=record.models.pic_upload_path, verbose_name='\u5c01\u9762'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('type_video', '\u89c6\u9891'), ('type_phtoto', '\u6444\u5f71'), ('type_travel', '\u6e38\u8bb0'), ('type_program', '\u7f16\u7a0b')], default='', max_length=20, verbose_name='\u7c7b\u578b'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u89c6\u9891\u94fe\u63a5'),
        ),
    ]
